AllCops:
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Max: 160

Metrics/ClassLength:
  Max: 310

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 240

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 50

Metrics/LineLength:
  Max: 120
  
Style/Documentation:
  Enabled: false

Style/IndentHeredoc:
  Enabled: false
  
Style/MutableConstant:
  Enabled: false
  
Style/PercentLiteralDelimiters:
  Enabled: false
